## Ejercicios de NumPy

1. Importa la librería de NumPy.

In [1]:
import numpy as np

2. Crea un array de 1 dimension y 10 elementos.

In [3]:
array = np.random.randint(0,100, (10))
array

array([60, 79, 84, 67, 71, 91, 71,  2, 20, 52])

3. Reemplaza todos los números impares por el valor "par" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [9]:
## entiendo que en el enunciado pedís que los impares los sustituyamos por el valor "impar" y los pares por "par" por lo que lo voy a hacer de esta manera:

In [27]:
array_vacio = np.where(array % 2 == 0, "par", "impar")
array_vacio

array(['par', 'impar', 'par', 'impar', 'impar', 'impar', 'impar', 'par',
       'par', 'par'], dtype='<U5')

4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [29]:
array_vacio.reshape(2, 5)

array([['par', 'impar', 'par', 'impar', 'impar'],
       ['impar', 'impar', 'par', 'par', 'par']], dtype='<U5')

5. Extrae los elementos comunes de los siguientes arrays

In [39]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [40]:
np.intersect1d(array1, array2)

array([2, 4])

6. Extraed los elementos que están en el array1 pero no en el array2.

In [42]:
np.setdiff1d(array1, array2)

array([1, 3, 5, 6])

7. Extraed las posiciones donde tengamos elementos que sean iguales.

In [45]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

array_comunes = np.intersect1d(array1, array2, return_indices=True)
array_comunes


# los elementos comunes son el 2 y el 4. Los número siguientes(1 y 5) corresponden a las posiciones en el primer array,
# los siguientes 1 y 5 corresponden a las posiciones del segundo array.
# el problema es que solo nos saca las primeras posiciones qu ha encontrado

(array([2, 4]), array([1, 5]), array([1, 5]))

In [56]:
# con el np.where sacamos las posiciones 2 y 4 en el array 1
indices2_array1 = np.where(array1 == 2)
indices4_array1 = np.where(array1 == 4)

print(indices2_array1)
print(indices4_array1)


(array([1, 3]),)
(array([5, 7]),)


In [57]:
# volvemos a sacar todas las posiciones del array 2
indices2_array2 = np.where(array2 == 2)
indices4_array2 = np.where(array2 == 4)

print(indices2_array2)
print(indices4_array2)

(array([1, 3]),)
(array([5, 7]),)


8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [59]:
array8 = np.random.randint(0,50, (3,5))
array8

array([[ 8, 46,  0, 30, 34],
       [20, 39,  5, 38, 40],
       [46, 20,  2, 10, 18]])

In [71]:

array8[array8 < 10]

array([8, 0, 5, 2])

In [72]:
array8[array8 > 40]

array([46, 46])

9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [104]:
# hemos creado un array de dimensiones 5x3 con random.rand para que nos sacara los números decimales 
array = np.random.rand(5,3)
array

array([[0.19629991, 0.81005476, 0.58189933],
       [0.91561442, 0.61645416, 0.18094774],
       [0.43805174, 0.89782963, 0.47613061],
       [0.4010951 , 0.6830379 , 0.09666809],
       [0.29895757, 0.01102847, 0.21244027]])

In [105]:
#y hemos ajustado el intervalo entre 5 y 10 multiplicando el array x5 y sumando 5.
array = 5 + array * 5
array

array([[5.98149955, 9.0502738 , 7.90949665],
       [9.57807208, 8.08227082, 5.90473868],
       [7.1902587 , 9.48914815, 7.38065307],
       [7.00547549, 8.41518952, 5.48334046],
       [6.49478786, 5.05514235, 6.06220134]])

10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20.
    - Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [107]:

array_tridimensional = np.random.randint(1,20, (2,4,7))
array_tridimensional

array([[[ 7, 15, 12,  7,  8,  6,  7],
        [14, 11, 18, 10, 17,  2, 13],
        [ 3, 10, 12,  5, 13,  9, 11],
        [16,  1, 16, 16,  6, 13,  1]],

       [[ 4,  9, 16, 11,  1, 11,  7],
        [12,  3,  3, 13, 17,  3, 11],
        [10,  3, 17,  1, 19,  6,  2],
        [16, 19, 11,  6, 12, 19,  3]]])

In [110]:
np.transpose(array_tridimensional, (1,2,0))

array([[[ 7,  4],
        [15,  9],
        [12, 16],
        [ 7, 11],
        [ 8,  1],
        [ 6, 11],
        [ 7,  7]],

       [[14, 12],
        [11,  3],
        [18,  3],
        [10, 13],
        [17, 17],
        [ 2,  3],
        [13, 11]],

       [[ 3, 10],
        [10,  3],
        [12, 17],
        [ 5,  1],
        [13, 19],
        [ 9,  6],
        [11,  2]],

       [[16, 16],
        [ 1, 19],
        [16, 11],
        [16,  6],
        [ 6, 12],
        [13, 19],
        [ 1,  3]]])